apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: mysql
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: 3306
  clusterIP: None
  selector:
    app: mysql