# deployment 配置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logic-deployment
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ .Values.server.logic.name }}
spec:
  replicas: {{ .Values.server.logic.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.server.logic.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.server.logic.name }}
    spec:
      imagePullSecrets:
        - name: aliyun-reg-secret
      containers:
        - name: {{ .Values.server.logic.name }}
          image: {{ .Values.server.logic.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /data/log/logic
              name: log
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ENV
              value: {{ $.Values.env }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: log
          hostPath:
            path: /data/log/logic
---
# service 配置
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.logic.name }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ .Values.server.logic.name }}
spec:
  selector:
    app: {{ .Values.server.logic.name }}
  ports:
    - name: rpc
      protocol: TCP
      port: 8000
      targetPort: 8000
